name: HR CI workflow

on:
  push:   # workflow kab run hoga

jobs:
  build:  # job ka naam
    runs-on: ubuntu-latest  # job kaha run hoga

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'